### ISSUE TITLE
figshare data

### ISSUE THREAD

**Issue by daikitake** [RobersonLab/2021_Paley_neurosarcoid_scRNASeq#1]
I accessed figshare, but I was requested "Log in to figshare".
How could I access the data?

Downloadable data, including raw UMI counts, TCR sequences, and BCR sequences: [FigShare Project](https://figshare.com/account/home#/projects/137667)

Many thanks in advance,
Daiki

**Comment by eroberson** [comment]
Hello Daiki! I had forgot to hit the final publish on the project. It should be live now and the link was updated to the correct URL.
