### ISSUE TITLE
Raw fastq files - would you be able to make them publicly avaiable

### ISSUE THREAD

**Issue by hoangmgh** [RobersonLab/2021_Paley_neurosarcoid_scRNASeq#2]
Hello to the team at the Roberson Lab, 
I was just wondering if we can have access to the raw fastq files for this dataset? This is a very interesting and insightful study, and we thought we can use this for our meta-analysis across multiple conditions using scRNA-seq of CSF.
Thanks in advance!

**Comment by eroberson** [comment]
Hello! I forwarded your request to the data owner when you emailed. Sorry I missed this first!
